[workspace]
resolver = "2"
members = ["crates/zgegc", "crates/pegme"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.11"
pretty_assertions = "1.4"
unicode-id-start = "1.4"
