#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 94
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 16

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_fun = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_DASH_GT = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_SEMI = 8,
  anon_sym_let = 9,
  anon_sym_COLON = 10,
  anon_sym_EQ = 11,
  anon_sym_return = 12,
  anon_sym_if = 13,
  anon_sym_else = 14,
  anon_sym_loop = 15,
  anon_sym_DASH = 16,
  anon_sym_PLUS = 17,
  anon_sym_BANG = 18,
  anon_sym_TILDE = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_BANG_EQ = 23,
  anon_sym_LT = 24,
  anon_sym_GT = 25,
  anon_sym_LT_EQ = 26,
  anon_sym_GT_EQ = 27,
  anon_sym_AMP_AMP = 28,
  anon_sym_PIPE_PIPE = 29,
  anon_sym_COMMA = 30,
  anon_sym_u8 = 31,
  anon_sym_i8 = 32,
  anon_sym_u16 = 33,
  anon_sym_i16 = 34,
  anon_sym_u32 = 35,
  anon_sym_i32 = 36,
  anon_sym_u64 = 37,
  anon_sym_i64 = 38,
  sym_number_literal = 39,
  sym_string_literal = 40,
  sym_source_file = 41,
  sym__item = 42,
  sym_function_item = 43,
  sym_block = 44,
  sym__statement = 45,
  sym__expression_statement = 46,
  sym_let_statement = 47,
  sym_assignement_statement = 48,
  sym_return_statement = 49,
  sym__expression = 50,
  sym__no_block_expression = 51,
  sym__block_expression = 52,
  sym_if_expression = 53,
  sym_loop_expression = 54,
  sym_unary_expression = 55,
  sym_binary_expression = 56,
  sym_function_call = 57,
  sym_type = 58,
  sym_builtin_type = 59,
  sym__literal = 60,
  aux_sym_source_file_repeat1 = 61,
  aux_sym_block_repeat1 = 62,
  aux_sym_if_expression_repeat1 = 63,
  aux_sym_function_call_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_fun] = "fun",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_loop] = "loop",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_BANG] = "!",
  [anon_sym_TILDE] = "~",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_COMMA] = ",",
  [anon_sym_u8] = "u8",
  [anon_sym_i8] = "i8",
  [anon_sym_u16] = "u16",
  [anon_sym_i16] = "i16",
  [anon_sym_u32] = "u32",
  [anon_sym_i32] = "i32",
  [anon_sym_u64] = "u64",
  [anon_sym_i64] = "i64",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_function_item] = "function_item",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym__expression_statement] = "_expression_statement",
  [sym_let_statement] = "let_statement",
  [sym_assignement_statement] = "assignement_statement",
  [sym_return_statement] = "return_statement",
  [sym__expression] = "_expression",
  [sym__no_block_expression] = "_no_block_expression",
  [sym__block_expression] = "_block_expression",
  [sym_if_expression] = "if_expression",
  [sym_loop_expression] = "loop_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_function_call] = "function_call",
  [sym_type] = "type",
  [sym_builtin_type] = "builtin_type",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_if_expression_repeat1] = "if_expression_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_i64] = anon_sym_i64,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_function_item] = sym_function_item,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym__expression_statement] = sym__expression_statement,
  [sym_let_statement] = sym_let_statement,
  [sym_assignement_statement] = sym_assignement_statement,
  [sym_return_statement] = sym_return_statement,
  [sym__expression] = sym__expression,
  [sym__no_block_expression] = sym__no_block_expression,
  [sym__block_expression] = sym__block_expression,
  [sym_if_expression] = sym_if_expression,
  [sym_loop_expression] = sym_loop_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_function_call] = sym_function_call,
  [sym_type] = sym_type,
  [sym_builtin_type] = sym_builtin_type,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_if_expression_repeat1] = aux_sym_if_expression_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_function_item] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignement_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__no_block_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__block_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_body = 2,
  field_initializer = 3,
  field_left = 4,
  field_name = 5,
  field_op = 6,
  field_place = 7,
  field_return_type = 8,
  field_return_value = 9,
  field_right = 10,
  field_statements = 11,
  field_type = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_initializer] = "initializer",
  [field_left] = "left",
  [field_name] = "name",
  [field_op] = "op",
  [field_place] = "place",
  [field_return_type] = "return_type",
  [field_return_value] = "return_value",
  [field_right] = "right",
  [field_statements] = "statements",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
  [4] = {.index = 7, .length = 1},
  [5] = {.index = 8, .length = 1},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 3},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 3},
  [14] = {.index = 25, .length = 4},
  [15] = {.index = 29, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 4},
    {field_name, 1},
  [2] =
    {field_body, 6},
    {field_name, 1},
    {field_return_type, 5},
  [5] =
    {field_op, 0},
    {field_value, 1},
  [7] =
    {field_statements, 1},
  [8] =
    {field_name, 1},
  [9] =
    {field_return_value, 1},
  [10] =
    {field_name, 0},
  [11] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [14] =
    {field_arguments, 2},
    {field_name, 0},
  [16] =
    {field_place, 0},
    {field_value, 2},
  [18] =
    {field_name, 1},
    {field_type, 3},
  [20] =
    {field_initializer, 3},
    {field_name, 1},
  [22] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_name, 0},
  [25] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_arguments, 4},
    {field_name, 0},
  [29] =
    {field_initializer, 5},
    {field_name, 1},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 2,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 18,
  [56] = 56,
  [57] = 12,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 65,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 71,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 51,
  [81] = 56,
  [82] = 82,
  [83] = 83,
  [84] = 82,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 90,
  [92] = 89,
  [93] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 22,
        '"', 2,
        '&', 3,
        '(', 10,
        ')', 11,
        '*', 24,
        '+', 20,
        ',', 34,
        '-', 19,
        '/', 25,
        ':', 16,
        ';', 15,
        '<', 28,
        '=', 17,
        '>', 29,
        '{', 13,
        '|', 7,
        '}', 14,
        '~', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 21,
        '"', 2,
        '(', 10,
        ')', 11,
        '+', 20,
        '-', 18,
        ';', 15,
        '}', 14,
        '~', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '{') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == '|') ADVANCE(33);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 5,
        '&', 3,
        '(', 10,
        ')', 11,
        '*', 24,
        '+', 20,
        ',', 34,
        '-', 18,
        '/', 25,
        ';', 15,
        '<', 28,
        '=', 17,
        '>', 29,
        '{', 13,
        '|', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(12);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '1') ADVANCE(9);
      if (lookahead == '3') ADVANCE(10);
      if (lookahead == '6') ADVANCE(11);
      if (lookahead == '8') ADVANCE(12);
      if (lookahead == 'f') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '1') ADVANCE(17);
      if (lookahead == '3') ADVANCE(18);
      if (lookahead == '6') ADVANCE(19);
      if (lookahead == '8') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '6') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == '2') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(25);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == '6') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == '2') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == '4') ADVANCE(31);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 8},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(85),
    [sym__item] = STATE(68),
    [sym_function_item] = STATE(68),
    [aux_sym_source_file_repeat1] = STATE(68),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fun] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_fun,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_return,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    STATE(64), 1,
      sym__expression,
    ACTIONS(25), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(3), 8,
      sym__item,
      sym_function_item,
      sym__statement,
      sym__expression_statement,
      sym_let_statement,
      sym_assignement_statement,
      sym_return_statement,
      aux_sym_block_repeat1,
    STATE(59), 8,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [58] = 13,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(30), 1,
      anon_sym_fun,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_return,
    ACTIONS(44), 1,
      anon_sym_if,
    ACTIONS(47), 1,
      anon_sym_loop,
    STATE(64), 1,
      sym__expression,
    ACTIONS(53), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(50), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(3), 8,
      sym__item,
      sym_function_item,
      sym__statement,
      sym__expression_statement,
      sym_let_statement,
      sym_assignement_statement,
      sym_return_statement,
      aux_sym_block_repeat1,
    STATE(59), 8,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [116] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_fun,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_return,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym__expression,
    ACTIONS(25), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(2), 8,
      sym__item,
      sym_function_item,
      sym__statement,
      sym__expression_statement,
      sym_let_statement,
      sym_assignement_statement,
      sym_return_statement,
      aux_sym_block_repeat1,
    STATE(59), 8,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [174] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_fun,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_return,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym__expression,
    ACTIONS(25), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(6), 8,
      sym__item,
      sym_function_item,
      sym__statement,
      sym__expression_statement,
      sym_let_statement,
      sym_assignement_statement,
      sym_return_statement,
      aux_sym_block_repeat1,
    STATE(59), 8,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [232] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_fun,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_return,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym__expression,
    ACTIONS(25), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(3), 8,
      sym__item,
      sym_function_item,
      sym__statement,
      sym__expression_statement,
      sym_let_statement,
      sym_assignement_statement,
      sym_return_statement,
      aux_sym_block_repeat1,
    STATE(59), 8,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [290] = 8,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(64), 1,
      anon_sym_SEMI,
    ACTIONS(66), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(58), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [327] = 8,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    ACTIONS(70), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(42), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [364] = 8,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    ACTIONS(74), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(50), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [401] = 8,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    ACTIONS(74), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(50), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [438] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(78), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(35), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [472] = 2,
    ACTIONS(82), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(80), 17,
      ts_builtin_sym_end,
      anon_sym_fun,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [496] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(84), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(44), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [530] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(86), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(60), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [564] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(88), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(31), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [598] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(90), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(29), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [632] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(92), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(30), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [666] = 2,
    ACTIONS(96), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(94), 17,
      ts_builtin_sym_end,
      anon_sym_fun,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [690] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(98), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(61), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [724] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(100), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(63), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [758] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(102), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(52), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [792] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(104), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(62), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [826] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_loop,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(74), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(23), 4,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
    STATE(50), 9,
      sym__expression,
      sym__no_block_expression,
      sym__block_expression,
      sym_if_expression,
      sym_loop_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_function_call,
      sym__literal,
  [860] = 4,
    ACTIONS(108), 1,
      anon_sym_else,
    STATE(25), 1,
      aux_sym_if_expression_repeat1,
    ACTIONS(110), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [887] = 4,
    ACTIONS(114), 1,
      anon_sym_else,
    STATE(26), 1,
      aux_sym_if_expression_repeat1,
    ACTIONS(116), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(112), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [914] = 4,
    ACTIONS(120), 1,
      anon_sym_else,
    STATE(26), 1,
      aux_sym_if_expression_repeat1,
    ACTIONS(123), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(118), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [941] = 2,
    ACTIONS(127), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 15,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_else,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [963] = 3,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [987] = 2,
    ACTIONS(137), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(135), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1008] = 4,
    ACTIONS(137), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(135), 10,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1033] = 3,
    ACTIONS(137), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(135), 12,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1056] = 2,
    ACTIONS(145), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(143), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1077] = 2,
    ACTIONS(149), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(147), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1098] = 2,
    ACTIONS(153), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(151), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1119] = 2,
    ACTIONS(157), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(155), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1140] = 2,
    ACTIONS(161), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(159), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1161] = 2,
    ACTIONS(165), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(163), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1182] = 2,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(167), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1203] = 2,
    ACTIONS(173), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(171), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1224] = 2,
    ACTIONS(177), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(175), 14,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_COMMA,
  [1245] = 4,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 1,
      anon_sym_EQ,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1269] = 7,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1299] = 2,
    ACTIONS(189), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(191), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1318] = 6,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_block,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1345] = 2,
    ACTIONS(195), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(197), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1364] = 2,
    ACTIONS(199), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(201), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1383] = 2,
    ACTIONS(203), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(205), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1402] = 2,
    ACTIONS(207), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(209), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1421] = 2,
    ACTIONS(211), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(213), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1440] = 5,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1465] = 2,
    ACTIONS(217), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(219), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1484] = 6,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_block,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1511] = 2,
    ACTIONS(221), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(223), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1530] = 2,
    ACTIONS(225), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(227), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1549] = 2,
    ACTIONS(96), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(94), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1568] = 2,
    ACTIONS(229), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(231), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1587] = 2,
    ACTIONS(82), 6,
      anon_sym_fun,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_loop,
      sym_identifier,
    ACTIONS(80), 8,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_TILDE,
      sym_number_literal,
      sym_string_literal,
  [1606] = 5,
    ACTIONS(233), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1630] = 3,
    ACTIONS(235), 1,
      anon_sym_SEMI,
    ACTIONS(239), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(237), 10,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1650] = 5,
    ACTIONS(241), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1674] = 5,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1698] = 5,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1722] = 5,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1746] = 4,
    ACTIONS(139), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1767] = 4,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(78), 1,
      sym_builtin_type,
    STATE(84), 1,
      sym_type,
    ACTIONS(251), 8,
      anon_sym_u8,
      anon_sym_i8,
      anon_sym_u16,
      anon_sym_i16,
      anon_sym_u32,
      anon_sym_i32,
      anon_sym_u64,
      anon_sym_i64,
  [1787] = 4,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(78), 1,
      sym_builtin_type,
    STATE(79), 1,
      sym_type,
    ACTIONS(251), 8,
      anon_sym_u8,
      anon_sym_i8,
      anon_sym_u16,
      anon_sym_i16,
      anon_sym_u32,
      anon_sym_i32,
      anon_sym_u64,
      anon_sym_i64,
  [1807] = 4,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(78), 1,
      sym_builtin_type,
    STATE(82), 1,
      sym_type,
    ACTIONS(251), 8,
      anon_sym_u8,
      anon_sym_i8,
      anon_sym_u16,
      anon_sym_i16,
      anon_sym_u32,
      anon_sym_i32,
      anon_sym_u64,
      anon_sym_i64,
  [1827] = 3,
    ACTIONS(5), 1,
      anon_sym_fun,
    ACTIONS(253), 1,
      ts_builtin_sym_end,
    STATE(69), 3,
      sym__item,
      sym_function_item,
      aux_sym_source_file_repeat1,
  [1839] = 3,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
    ACTIONS(257), 1,
      anon_sym_fun,
    STATE(69), 3,
      sym__item,
      sym_function_item,
      aux_sym_source_file_repeat1,
  [1851] = 3,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    ACTIONS(260), 1,
      anon_sym_if,
    STATE(37), 1,
      sym_block,
  [1861] = 3,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    ACTIONS(262), 1,
      anon_sym_DASH_GT,
    STATE(81), 1,
      sym_block,
  [1871] = 3,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_function_call_repeat1,
  [1881] = 3,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_function_call_repeat1,
  [1891] = 3,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    ACTIONS(260), 1,
      anon_sym_if,
    STATE(36), 1,
      sym_block,
  [1901] = 3,
    ACTIONS(269), 1,
      anon_sym_SEMI,
    ACTIONS(271), 1,
      anon_sym_COLON,
    ACTIONS(273), 1,
      anon_sym_EQ,
  [1911] = 3,
    ACTIONS(275), 1,
      anon_sym_DASH_GT,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      sym_block,
  [1921] = 1,
    ACTIONS(279), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
  [1927] = 1,
    ACTIONS(281), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
  [1933] = 2,
    ACTIONS(283), 1,
      anon_sym_SEMI,
    ACTIONS(285), 1,
      anon_sym_EQ,
  [1940] = 1,
    ACTIONS(219), 2,
      ts_builtin_sym_end,
      anon_sym_fun,
  [1945] = 1,
    ACTIONS(231), 2,
      ts_builtin_sym_end,
      anon_sym_fun,
  [1950] = 2,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_block,
  [1957] = 2,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_block,
  [1964] = 2,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_block,
  [1971] = 1,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
  [1975] = 1,
    ACTIONS(260), 1,
      anon_sym_if,
  [1979] = 1,
    ACTIONS(289), 1,
      sym_identifier,
  [1983] = 1,
    ACTIONS(291), 1,
      sym_identifier,
  [1987] = 1,
    ACTIONS(293), 1,
      anon_sym_LPAREN,
  [1991] = 1,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
  [1995] = 1,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
  [1999] = 1,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
  [2003] = 1,
    ACTIONS(301), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 58,
  [SMALL_STATE(4)] = 116,
  [SMALL_STATE(5)] = 174,
  [SMALL_STATE(6)] = 232,
  [SMALL_STATE(7)] = 290,
  [SMALL_STATE(8)] = 327,
  [SMALL_STATE(9)] = 364,
  [SMALL_STATE(10)] = 401,
  [SMALL_STATE(11)] = 438,
  [SMALL_STATE(12)] = 472,
  [SMALL_STATE(13)] = 496,
  [SMALL_STATE(14)] = 530,
  [SMALL_STATE(15)] = 564,
  [SMALL_STATE(16)] = 598,
  [SMALL_STATE(17)] = 632,
  [SMALL_STATE(18)] = 666,
  [SMALL_STATE(19)] = 690,
  [SMALL_STATE(20)] = 724,
  [SMALL_STATE(21)] = 758,
  [SMALL_STATE(22)] = 792,
  [SMALL_STATE(23)] = 826,
  [SMALL_STATE(24)] = 860,
  [SMALL_STATE(25)] = 887,
  [SMALL_STATE(26)] = 914,
  [SMALL_STATE(27)] = 941,
  [SMALL_STATE(28)] = 963,
  [SMALL_STATE(29)] = 987,
  [SMALL_STATE(30)] = 1008,
  [SMALL_STATE(31)] = 1033,
  [SMALL_STATE(32)] = 1056,
  [SMALL_STATE(33)] = 1077,
  [SMALL_STATE(34)] = 1098,
  [SMALL_STATE(35)] = 1119,
  [SMALL_STATE(36)] = 1140,
  [SMALL_STATE(37)] = 1161,
  [SMALL_STATE(38)] = 1182,
  [SMALL_STATE(39)] = 1203,
  [SMALL_STATE(40)] = 1224,
  [SMALL_STATE(41)] = 1245,
  [SMALL_STATE(42)] = 1269,
  [SMALL_STATE(43)] = 1299,
  [SMALL_STATE(44)] = 1318,
  [SMALL_STATE(45)] = 1345,
  [SMALL_STATE(46)] = 1364,
  [SMALL_STATE(47)] = 1383,
  [SMALL_STATE(48)] = 1402,
  [SMALL_STATE(49)] = 1421,
  [SMALL_STATE(50)] = 1440,
  [SMALL_STATE(51)] = 1465,
  [SMALL_STATE(52)] = 1484,
  [SMALL_STATE(53)] = 1511,
  [SMALL_STATE(54)] = 1530,
  [SMALL_STATE(55)] = 1549,
  [SMALL_STATE(56)] = 1568,
  [SMALL_STATE(57)] = 1587,
  [SMALL_STATE(58)] = 1606,
  [SMALL_STATE(59)] = 1630,
  [SMALL_STATE(60)] = 1650,
  [SMALL_STATE(61)] = 1674,
  [SMALL_STATE(62)] = 1698,
  [SMALL_STATE(63)] = 1722,
  [SMALL_STATE(64)] = 1746,
  [SMALL_STATE(65)] = 1767,
  [SMALL_STATE(66)] = 1787,
  [SMALL_STATE(67)] = 1807,
  [SMALL_STATE(68)] = 1827,
  [SMALL_STATE(69)] = 1839,
  [SMALL_STATE(70)] = 1851,
  [SMALL_STATE(71)] = 1861,
  [SMALL_STATE(72)] = 1871,
  [SMALL_STATE(73)] = 1881,
  [SMALL_STATE(74)] = 1891,
  [SMALL_STATE(75)] = 1901,
  [SMALL_STATE(76)] = 1911,
  [SMALL_STATE(77)] = 1921,
  [SMALL_STATE(78)] = 1927,
  [SMALL_STATE(79)] = 1933,
  [SMALL_STATE(80)] = 1940,
  [SMALL_STATE(81)] = 1945,
  [SMALL_STATE(82)] = 1950,
  [SMALL_STATE(83)] = 1957,
  [SMALL_STATE(84)] = 1964,
  [SMALL_STATE(85)] = 1971,
  [SMALL_STATE(86)] = 1975,
  [SMALL_STATE(87)] = 1979,
  [SMALL_STATE(88)] = 1983,
  [SMALL_STATE(89)] = 1987,
  [SMALL_STATE(90)] = 1991,
  [SMALL_STATE(91)] = 1995,
  [SMALL_STATE(92)] = 1999,
  [SMALL_STATE(93)] = 2003,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 4),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 4),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_expression_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_expression_repeat1, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__no_block_expression, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__no_block_expression, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 8),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 8),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 9),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 9),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_expression, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_expression, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__no_block_expression, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__no_block_expression, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 3),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 6, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 6, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 13),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 13),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 6, 0, 14),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 6, 0, 14),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 7),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 7),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 3, 0, 5),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 3, 0, 5),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 6),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 6),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, 0, 11),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 11),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignement_statement, 4, 0, 10),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignement_statement, 4, 0, 10),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, 0, 12),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 12),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_item, 7, 0, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 7, 0, 2),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 7, 0, 15),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 7, 0, 15),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_statement, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_statement, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_item, 5, 0, 1),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_item, 5, 0, 1),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_type, 1, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [287] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zgeg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
