[package]
name = "zgegc"
version.workspace = true
edition.workspace = true

[dependencies]
pegme = { path = "../pegme" }
clap.workspace = true
tracing.workspace = true

[build-dependencies]
pegme = { path = "../pegme" }
pegme_codegen = { path = "../pegme_codegen" }
